### ISSUE TITLE
custom temp dir

### ISSUE THREAD

**Issue by daler** [brentp/shuffler#2]
What's the best way to specify a custom temp dir?  This would be useful because nodes on our cluster use /scratch rather than /tmp.

One way would be to add, in `__main__.main()`, 

```
    p.add_argument('--tempdir', help='temp dir to use, default is /tmp', default='/tmp')
```

and then 

```
tempfile.tempdir = args.tempdir
```

and then remove all the `dir="/tmp/"` kwargs from all the mktemp calls.  This will let all the mktemp calls use the default tempfile module-level dir by default.

Side note: `mktemp()` is [deprecated according to the docs](http://docs.python.org/2/library/tempfile.html#tempfile.mktemp), replacement is `NamedTemporaryFile.name`

I can make the edits and send a pull request if you think this is reasonable.

**Comment by brentp** [comment]
either that or grabbing tempdir from os.environ.get("TMPDIR", "/tmp/") since that's an environment variable anyway. I don't have a preference for either.

I'll work on the mktemp() stuff by writing a function to return all temp files for the module--though I always do that and prefer the simplicity.

**Comment by brentp** [comment]
how about this: https://github.com/brentp/shuffler/commit/979350d8197d601aa859d2ea4bb12ea9b85cf463 ?

**Comment by daler** [comment]
Yep that works, thanks. Plus, this method is more consistent -- than the tempfile.tempdir method --  with the "shell-centric" architecture of the package
